apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinetest
  labels:
    app: pipelinetest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipelinetest
  template:
    metadata:
      labels:
        app: pipelinetest
    spec:
      containers:
        - name: pipelinetest
          image: localhost:30500/pipelinetest:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
