apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinetest
  labels:
    app: pipelinetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinetest
  template:
    metadata:
      labels:
        app: pipelinetest
    spec:
      containers:
        - name: pipelinetest
          image: localhost:30500/pipelinetest:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 50m
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: pipelinetest-service
spec:
  type: NodePort
  selector:
    app: pipelinetest
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30300
